/** Authored strings settings; times in seconds, cutoff and motion in Hz. */
import type { ScoringRow } from './presetsScoringVoice';

export const STRINGS_ROWS: readonly ScoringRow[] = [
  [
    'Drowned Cellos',
    'bow',
    520.0,
    1.0,
    0.16,
    0.65,
    3.0,
    1.8,
    0.12,
    'dark bowed low',
    'Play C2–C4; hold 3–6 seconds. Keep room send subtle.',
  ],
  [
    'Estuary Violas',
    'bow',
    1100.0,
    2.0,
    0.2,
    0.48,
    2.5,
    1.6,
    0.17,
    'warm bowed ensemble',
    'Play C3–C5 in open fifths; a little plate blends the attacks.',
  ],
  [
    'Salt Violins',
    'bow',
    2100.0,
    3.0,
    0.13,
    0.35,
    2.0,
    1.3,
    0.24,
    'airy bowed ensemble',
    'Play C4–C6; use soft velocity for distant upper lines.',
  ],
  [
    'Muted Chamber',
    'silk',
    850.0,
    1.0,
    0.12,
    0.28,
    1.8,
    0.9,
    0.09,
    'muted intimate soft',
    'Play C3–C5; close triads and short releases suit sparse scoring.',
  ],
  [
    'Frozen Bow',
    'glass',
    1800.0,
    2.01,
    0.35,
    1.4,
    4.0,
    3.0,
    0.07,
    'cold bowed tension',
    'Play C3–C5; hold slowly for the glassy beating to emerge.',
  ],
  [
    'Rust Ensemble',
    'bow',
    1350.0,
    1.414,
    0.38,
    0.8,
    3.5,
    2.2,
    0.19,
    'rough bowed tension',
    'Play C2–C4; single notes or fifths keep the inharmonic edge clear.',
  ],
  [
    'Low Tremolo',
    'bow',
    620.0,
    2.0,
    0.3,
    0.18,
    1.6,
    0.65,
    3.2,
    'dark restless low',
    'Play C2–C3; quick drift in FM brightness gives restless bow texture.',
  ],
  [
    'High Tremolo',
    'bow',
    2600.0,
    3.0,
    0.28,
    0.12,
    1.2,
    0.55,
    4.6,
    'bright restless high',
    'Play C4–C5; repeat short notes under a quieter sustained voice.',
  ],
  [
    'Hollow Bows',
    'choir',
    730.0,
    1.0,
    0.18,
    0.9,
    3.0,
    2.0,
    0.11,
    'hollow bowed soft',
    'Play C3–C4; bandpassed body leaves room for a separate bass.',
  ],
  [
    'Violet Section',
    'silk',
    1550.0,
    2.5,
    0.25,
    0.6,
    2.8,
    2.4,
    0.14,
    'lush warm ensemble',
    'Play C3–C5; leave space between chord changes for the release.',
  ],
  [
    'Wire Harmonics',
    'glass',
    3400.0,
    4.0,
    0.24,
    0.2,
    2.4,
    2.0,
    0.21,
    'harmonics thin cold',
    'Play C4–C6; isolated notes or octave doubles with plate.',
  ],
  [
    'Silt Contrabass',
    'bow',
    290.0,
    0.5,
    0.21,
    1.1,
    4.0,
    2.8,
    0.06,
    'dark low bowed',
    'Play C2–C3; slow roots under upper-register atmosphere.',
  ],
  [
    'Breathing Rosin',
    'bow',
    1750.0,
    1.5,
    0.42,
    1.8,
    4.5,
    3.2,
    0.32,
    'rough evolving bowed',
    'Hold C3–C4 for 5 seconds or longer; sparse voicings.',
  ],
  [
    'Afterimage Quartet',
    'silk',
    1250.0,
    3.0,
    0.19,
    0.42,
    2.2,
    1.5,
    0.08,
    'soft intimate warm',
    'Play C3–C5; restrained three-note chords and modest room send.',
  ],
  [
    'Black Ice Strings',
    'glass',
    950.0,
    2.718,
    0.48,
    2.2,
    5.0,
    4.0,
    0.05,
    'cold tension slow',
    'Hold C3–C5 for 6–8 seconds; the slow FM bloom is the gesture.',
  ],
  [
    'Remote Orchestra',
    'bow',
    780.0,
    2.0,
    0.1,
    2.8,
    5.0,
    4.5,
    0.04,
    'distant slow ensemble',
    'Play C3–C5; long open chords with a generous plate send.',
  ],
];
