/** Authored soundtrack fx settings; times in seconds, cutoff and motion in Hz. */
import type { ScoringRow } from './presetsScoringVoice';

export const SOUNDTRACKFX_ROWS: readonly ScoringRow[] = [
  [
    'Vent Breath',
    'air',
    650.0,
    1.0,
    0.12,
    1.2,
    3.0,
    1.8,
    0.12,
    'noise whoosh dark',
    'Hold 3–5 seconds; the filter shapes the noise, keyboard pitch is secondary.',
  ],
  [
    'Silk Swish',
    'air',
    2800.0,
    2.0,
    0.16,
    0.08,
    0.5,
    0.4,
    0.4,
    'noise swish airy',
    'Tap and release after half a second for a short transition.',
  ],
  [
    'Slow Air Riser',
    'rise',
    180.0,
    1.0,
    0.2,
    6.0,
    2.0,
    1.2,
    0.08,
    'noise riser slow',
    'Hold 6–8 seconds: the filter opens four octaves; release at the transition.',
  ],
  [
    'Narrow Riser',
    'rise',
    420.0,
    2.0,
    0.3,
    3.0,
    1.0,
    0.65,
    0.2,
    'noise riser tense',
    'Hold at least 3 seconds; a narrower, brighter build.',
  ],
  [
    'Long Downwash',
    'fall',
    200.0,
    1.0,
    0.15,
    0.005,
    5.0,
    2.0,
    0.07,
    'noise downlifter dark',
    'Hold 5 seconds so the descending filter completes before release.',
  ],
  [
    'Quick Downwash',
    'fall',
    520.0,
    2.0,
    0.25,
    0.003,
    1.2,
    0.6,
    0.25,
    'noise downlifter short',
    'Hold about 1.5 seconds; short filtered-noise transition.',
  ],
  [
    'Radio Dust',
    'air',
    4200.0,
    3.0,
    0.45,
    0.03,
    1.0,
    0.3,
    2.4,
    'noise static thin',
    'Hold for a static bed; bandpass removes most low-frequency weight.',
  ],
  [
    'Deep Static',
    'air',
    320.0,
    0.5,
    0.5,
    0.4,
    2.0,
    1.0,
    0.8,
    'noise static dark',
    'Hold 2–4 seconds beneath a sparse tonal layer.',
  ],
  [
    'Dry Ticker',
    'pulse',
    1800.0,
    4.7,
    0.55,
    0.001,
    0.2,
    0.08,
    6.0,
    'ticker rhythmic metallic',
    'Hold C3–C5; amplitude pulses at 6 Hz, not tempo-synced.',
  ],
  [
    'Hollow Ticker',
    'pulse',
    800.0,
    2.414,
    0.4,
    0.002,
    0.4,
    0.15,
    3.0,
    'ticker hollow rhythmic',
    'Hold C3–C4; 3 Hz pulse, or retrigger notes with the sequencer.',
  ],
  [
    'Slow Beacon',
    'pulse',
    240.0,
    1.5,
    0.3,
    0.2,
    2.0,
    1.0,
    0.5,
    'pulser slow tension',
    'Hold C3–C4; one amplitude cycle every two seconds.',
  ],
  [
    'Engine Pulser',
    'pulse',
    560.0,
    3.141,
    0.65,
    0.05,
    1.2,
    0.5,
    2.0,
    'pulser mechanical tension',
    'Hold C2–C4; 2 Hz gating for a steady mechanical bed.',
  ],
  [
    'Broken Relay',
    'glitch',
    1500.0,
    3.7,
    0.7,
    0.002,
    0.3,
    0.12,
    9.0,
    'glitch digital short',
    'Play short C3–C5 notes; sample-and-hold pitch and filter jumps.',
  ],
  [
    'Data Fragments',
    'glitch',
    2600.0,
    5.31,
    0.55,
    0.001,
    0.18,
    0.08,
    15.0,
    'glitch digital thin',
    'Play C4–C5 bursts with rests; highpass makes a thin brittle layer.',
  ],
  [
    'Corrupt Clock',
    'glitch',
    700.0,
    1.414,
    0.8,
    0.01,
    1.0,
    0.35,
    4.0,
    'glitch unstable rhythmic',
    'Hold C3–C4; irregular timbre at a 4 Hz update rate.',
  ],
  [
    'Buffer Drift',
    'glitch',
    350.0,
    2.718,
    0.45,
    0.3,
    2.0,
    1.2,
    0.7,
    'glitch slow dark',
    'Hold C3–C4 for several seconds; slow random pitch steps.',
  ],
  [
    'Suspended Steel',
    'metal',
    420.0,
    1.414,
    0.8,
    1.8,
    4.0,
    3.0,
    0.12,
    'atonal metal tension',
    'Hold C2–C4 single notes; inharmonic FM builds a suspended metallic bed.',
  ],
  [
    'Distant Gantry',
    'metal',
    260.0,
    2.414,
    0.65,
    2.5,
    5.0,
    4.0,
    0.06,
    'atonal vast low',
    'Hold C2–C3 for 6 seconds; add plate to suggest distance.',
  ],
  [
    'Wire Stress',
    'metal',
    1400.0,
    5.17,
    0.95,
    0.4,
    3.0,
    2.0,
    0.3,
    'atonal thin tension',
    'Hold C3–C5; keep mixer level low beneath the scene.',
  ],
  [
    'Black Resonator',
    'metal',
    180.0,
    0.707,
    0.9,
    3.5,
    6.0,
    4.5,
    0.045,
    'atonal dark vast',
    'Hold C2–C3 for 8 seconds; slow inharmonic tension.',
  ],
  [
    'Passing Vapour',
    'air',
    1500.0,
    1.5,
    0.22,
    0.65,
    1.4,
    0.8,
    0.18,
    'noise whoosh soft',
    'Hold 1–2 seconds then release; manually place ahead of a cut.',
  ],
  [
    'Bright Air Riser',
    'rise',
    800.0,
    3.0,
    0.35,
    1.5,
    0.6,
    0.35,
    0.35,
    'noise riser bright',
    'Hold at least 1.5 seconds; short high-frequency transition.',
  ],
  [
    'Granular Hiss',
    'air',
    6200.0,
    4.0,
    0.6,
    0.02,
    0.8,
    0.25,
    7.0,
    'noise static restless',
    'Hold briefly at low mix level; fast drift roughens the filtered hiss.',
  ],
  [
    'Uneasy Scale',
    'metal',
    620.0,
    1.618,
    0.5,
    0.8,
    3.5,
    2.5,
    0.16,
    'atonal eerie sparse',
    'Play widely spaced C3–C5 notes; suggests scale of a space, not a tonal scale.',
  ],
];
