// Generated by scripts/patch-library-index.mjs from the files beside it — do not edit.
// `node scripts/patch-library-index.mjs --write` regenerates it; `npm run verify` checks it.
// One static import per patch is what Vite, esbuild and Vitest all bundle (#561).
import patch_ai_voice from './ai-voice.json';
import patch_bass_digital from './bass-digital.json';
import patch_build_thunk from './build-thunk.json';
import patch_drone_sqr from './drone-sqr.json';
import patch_efm_bell_perc from './efm-bell-perc.json';
import patch_efm_clap from './efm-clap.json';
import patch_efm_cowbell from './efm-cowbell.json';
import patch_efm_crash from './efm-crash.json';
import patch_efm_hat_closed from './efm-hat-closed.json';
import patch_efm_hat_open from './efm-hat-open.json';
import patch_efm_kick from './efm-kick.json';
import patch_efm_rim from './efm-rim.json';
import patch_efm_snare from './efm-snare.json';
import patch_efm_tom from './efm-tom.json';
import patch_efm_zap from './efm-zap.json';
import patch_hat from './hat.json';
import patch_horde_horn from './horde-horn.json';
import patch_kick from './kick.json';
import patch_lead_bell from './lead-bell.json';
import patch_pad_drift from './pad-drift.json';
import patch_pickup_blip from './pickup-blip.json';
import patch_saw_arp from './saw-arp.json';
import patch_score_afterimage_quartet from './score-afterimage-quartet.json';
import patch_score_amber_ceiling from './score-amber-ceiling.json';
import patch_score_amber_stab from './score-amber-stab.json';
import patch_score_ash_cathedral from './score-ash-cathedral.json';
import patch_score_black_ice_strings from './score-black-ice-strings.json';
import patch_score_black_resonator from './score-black-resonator.json';
import patch_score_blue_vapour from './score-blue-vapour.json';
import patch_score_breathing_rosin from './score-breathing-rosin.json';
import patch_score_bright_air_riser from './score-bright-air-riser.json';
import patch_score_broken_relay from './score-broken-relay.json';
import patch_score_bronze_rain from './score-bronze-rain.json';
import patch_score_buffer_drift from './score-buffer-drift.json';
import patch_score_buried_voices from './score-buried-voices.json';
import patch_score_carbon_reed from './score-carbon-reed.json';
import patch_score_concrete_chord from './score-concrete-chord.json';
import patch_score_copper_step from './score-copper-step.json';
import patch_score_corrupt_clock from './score-corrupt-clock.json';
import patch_score_data_fragments from './score-data-fragments.json';
import patch_score_deep_current from './score-deep-current.json';
import patch_score_deep_static from './score-deep-static.json';
import patch_score_distant_gantry from './score-distant-gantry.json';
import patch_score_dockside_bass from './score-dockside-bass.json';
import patch_score_drowned_cellos from './score-drowned-cellos.json';
import patch_score_dry_relay from './score-dry-relay.json';
import patch_score_dry_ticker from './score-dry-ticker.json';
import patch_score_empty_station from './score-empty-station.json';
import patch_score_engine_pulser from './score-engine-pulser.json';
import patch_score_estuary_violas from './score-estuary-violas.json';
import patch_score_faded_neon from './score-faded-neon.json';
import patch_score_felt_circuit from './score-felt-circuit.json';
import patch_score_felt_sub from './score-felt-sub.json';
import patch_score_frozen_bow from './score-frozen-bow.json';
import patch_score_ghost_formants from './score-ghost-formants.json';
import patch_score_glass_horizon from './score-glass-horizon.json';
import patch_score_glass_pebble from './score-glass-pebble.json';
import patch_score_granular_hiss from './score-granular-hiss.json';
import patch_score_graphite_bass from './score-graphite-bass.json';
import patch_score_harbour_fog from './score-harbour-fog.json';
import patch_score_high_tremolo from './score-high-tremolo.json';
import patch_score_hollow_anchor from './score-hollow-anchor.json';
import patch_score_hollow_bows from './score-hollow-bows.json';
import patch_score_hollow_droplet from './score-hollow-droplet.json';
import patch_score_hollow_ticker from './score-hollow-ticker.json';
import patch_score_ice_needle from './score-ice-needle.json';
import patch_score_iron_root from './score-iron-root.json';
import patch_score_last_light_bell from './score-last-light-bell.json';
import patch_score_long_downwash from './score-long-downwash.json';
import patch_score_long_dusk from './score-long-dusk.json';
import patch_score_low_transformer from './score-low-transformer.json';
import patch_score_low_tremolo from './score-low-tremolo.json';
import patch_score_low_weather from './score-low-weather.json';
import patch_score_magnetic_veil from './score-magnetic-veil.json';
import patch_score_moss_stab from './score-moss-stab.json';
import patch_score_muted_cable from './score-muted-cable.json';
import patch_score_muted_chamber from './score-muted-chamber.json';
import patch_score_narrow_riser from './score-narrow-riser.json';
import patch_score_night_choir from './score-night-choir.json';
import patch_score_night_rubber from './score-night-rubber.json';
import patch_score_open_sea from './score-open-sea.json';
import patch_score_pale_monolith from './score-pale-monolith.json';
import patch_score_passing_vapour from './score-passing-vapour.json';
import patch_score_polar_bloom from './score-polar-bloom.json';
import patch_score_porcelain_drop from './score-porcelain-drop.json';
import patch_score_quick_downwash from './score-quick-downwash.json';
import patch_score_quiet_reactor from './score-quiet-reactor.json';
import patch_score_radio_dust from './score-radio-dust.json';
import patch_score_remote_orchestra from './score-remote-orchestra.json';
import patch_score_round_foundation from './score-round-foundation.json';
import patch_score_rubber_key from './score-rubber-key.json';
import patch_score_rust_ensemble from './score-rust-ensemble.json';
import patch_score_rusted_tine from './score-rusted-tine.json';
import patch_score_salt_violins from './score-salt-violins.json';
import patch_score_shortwave_chord from './score-shortwave-chord.json';
import patch_score_silk_swish from './score-silk-swish.json';
import patch_score_silt_contrabass from './score-silt-contrabass.json';
import patch_score_silt_pulse_bass from './score-silt-pulse-bass.json';
import patch_score_silver_dust from './score-silver-dust.json';
import patch_score_sine_weight from './score-sine-weight.json';
import patch_score_slow_air_riser from './score-slow-air-riser.json';
import patch_score_slow_beacon from './score-slow-beacon.json';
import patch_score_soft_machinery from './score-soft-machinery.json';
import patch_score_soft_undertow from './score-soft-undertow.json';
import patch_score_stone_marimba from './score-stone-marimba.json';
import patch_score_submerged_keys from './score-submerged-keys.json';
import patch_score_suspended_steel from './score-suspended-steel.json';
import patch_score_tape_halo from './score-tape-halo.json';
import patch_score_tidal_memory from './score-tidal-memory.json';
import patch_score_tin_kalimba from './score-tin-kalimba.json';
import patch_score_tunnel_growl from './score-tunnel-growl.json';
import patch_score_underwater_room from './score-underwater-room.json';
import patch_score_uneasy_scale from './score-uneasy-scale.json';
import patch_score_velvet_airlock from './score-velvet-airlock.json';
import patch_score_velvet_offbeat from './score-velvet-offbeat.json';
import patch_score_vent_breath from './score-vent-breath.json';
import patch_score_violet_section from './score-violet-section.json';
import patch_score_warm_pressure from './score-warm-pressure.json';
import patch_score_wire_harmonics from './score-wire-harmonics.json';
import patch_score_wire_harp from './score-wire-harp.json';
import patch_score_wire_stress from './score-wire-stress.json';
import patch_score_wooden_pin from './score-wooden-pin.json';
import patch_snare from './snare.json';
import patch_sub_drone from './sub-drone.json';
import patch_tr808_clap from './tr808-clap.json';
import patch_tr808_clave from './tr808-clave.json';
import patch_tr808_conga from './tr808-conga.json';
import patch_tr808_cowbell from './tr808-cowbell.json';
import patch_tr808_cymbal from './tr808-cymbal.json';
import patch_tr808_hat_closed from './tr808-hat-closed.json';
import patch_tr808_hat_open from './tr808-hat-open.json';
import patch_tr808_kick_long from './tr808-kick-long.json';
import patch_tr808_kick from './tr808-kick.json';
import patch_tr808_maracas from './tr808-maracas.json';
import patch_tr808_rimshot from './tr808-rimshot.json';
import patch_tr808_snare from './tr808-snare.json';
import patch_tr808_tom_high from './tr808-tom-high.json';
import patch_tr808_tom_low from './tr808-tom-low.json';
import patch_tr808_tom_mid from './tr808-tom-mid.json';
import patch_tr909_clap from './tr909-clap.json';
import patch_tr909_crash from './tr909-crash.json';
import patch_tr909_hat_closed from './tr909-hat-closed.json';
import patch_tr909_hat_open from './tr909-hat-open.json';
import patch_tr909_kick_hard from './tr909-kick-hard.json';
import patch_tr909_kick from './tr909-kick.json';
import patch_tr909_ride from './tr909-ride.json';
import patch_tr909_rimshot from './tr909-rimshot.json';
import patch_tr909_snare from './tr909-snare.json';
import patch_tr909_tom_high from './tr909-tom-high.json';
import patch_tr909_tom_low from './tr909-tom-low.json';
import patch_weapon_zap from './weapon-zap.json';

/** Every library file, raw and unvalidated, keyed by id (`presets.ts` loads it). */
export const PATCH_FILES: Readonly<Record<string, unknown>> = {
  'ai-voice': patch_ai_voice,
  'bass-digital': patch_bass_digital,
  'build-thunk': patch_build_thunk,
  'drone-sqr': patch_drone_sqr,
  'efm-bell-perc': patch_efm_bell_perc,
  'efm-clap': patch_efm_clap,
  'efm-cowbell': patch_efm_cowbell,
  'efm-crash': patch_efm_crash,
  'efm-hat-closed': patch_efm_hat_closed,
  'efm-hat-open': patch_efm_hat_open,
  'efm-kick': patch_efm_kick,
  'efm-rim': patch_efm_rim,
  'efm-snare': patch_efm_snare,
  'efm-tom': patch_efm_tom,
  'efm-zap': patch_efm_zap,
  hat: patch_hat,
  'horde-horn': patch_horde_horn,
  kick: patch_kick,
  'lead-bell': patch_lead_bell,
  'pad-drift': patch_pad_drift,
  'pickup-blip': patch_pickup_blip,
  'saw-arp': patch_saw_arp,
  'score-afterimage-quartet': patch_score_afterimage_quartet,
  'score-amber-ceiling': patch_score_amber_ceiling,
  'score-amber-stab': patch_score_amber_stab,
  'score-ash-cathedral': patch_score_ash_cathedral,
  'score-black-ice-strings': patch_score_black_ice_strings,
  'score-black-resonator': patch_score_black_resonator,
  'score-blue-vapour': patch_score_blue_vapour,
  'score-breathing-rosin': patch_score_breathing_rosin,
  'score-bright-air-riser': patch_score_bright_air_riser,
  'score-broken-relay': patch_score_broken_relay,
  'score-bronze-rain': patch_score_bronze_rain,
  'score-buffer-drift': patch_score_buffer_drift,
  'score-buried-voices': patch_score_buried_voices,
  'score-carbon-reed': patch_score_carbon_reed,
  'score-concrete-chord': patch_score_concrete_chord,
  'score-copper-step': patch_score_copper_step,
  'score-corrupt-clock': patch_score_corrupt_clock,
  'score-data-fragments': patch_score_data_fragments,
  'score-deep-current': patch_score_deep_current,
  'score-deep-static': patch_score_deep_static,
  'score-distant-gantry': patch_score_distant_gantry,
  'score-dockside-bass': patch_score_dockside_bass,
  'score-drowned-cellos': patch_score_drowned_cellos,
  'score-dry-relay': patch_score_dry_relay,
  'score-dry-ticker': patch_score_dry_ticker,
  'score-empty-station': patch_score_empty_station,
  'score-engine-pulser': patch_score_engine_pulser,
  'score-estuary-violas': patch_score_estuary_violas,
  'score-faded-neon': patch_score_faded_neon,
  'score-felt-circuit': patch_score_felt_circuit,
  'score-felt-sub': patch_score_felt_sub,
  'score-frozen-bow': patch_score_frozen_bow,
  'score-ghost-formants': patch_score_ghost_formants,
  'score-glass-horizon': patch_score_glass_horizon,
  'score-glass-pebble': patch_score_glass_pebble,
  'score-granular-hiss': patch_score_granular_hiss,
  'score-graphite-bass': patch_score_graphite_bass,
  'score-harbour-fog': patch_score_harbour_fog,
  'score-high-tremolo': patch_score_high_tremolo,
  'score-hollow-anchor': patch_score_hollow_anchor,
  'score-hollow-bows': patch_score_hollow_bows,
  'score-hollow-droplet': patch_score_hollow_droplet,
  'score-hollow-ticker': patch_score_hollow_ticker,
  'score-ice-needle': patch_score_ice_needle,
  'score-iron-root': patch_score_iron_root,
  'score-last-light-bell': patch_score_last_light_bell,
  'score-long-downwash': patch_score_long_downwash,
  'score-long-dusk': patch_score_long_dusk,
  'score-low-transformer': patch_score_low_transformer,
  'score-low-tremolo': patch_score_low_tremolo,
  'score-low-weather': patch_score_low_weather,
  'score-magnetic-veil': patch_score_magnetic_veil,
  'score-moss-stab': patch_score_moss_stab,
  'score-muted-cable': patch_score_muted_cable,
  'score-muted-chamber': patch_score_muted_chamber,
  'score-narrow-riser': patch_score_narrow_riser,
  'score-night-choir': patch_score_night_choir,
  'score-night-rubber': patch_score_night_rubber,
  'score-open-sea': patch_score_open_sea,
  'score-pale-monolith': patch_score_pale_monolith,
  'score-passing-vapour': patch_score_passing_vapour,
  'score-polar-bloom': patch_score_polar_bloom,
  'score-porcelain-drop': patch_score_porcelain_drop,
  'score-quick-downwash': patch_score_quick_downwash,
  'score-quiet-reactor': patch_score_quiet_reactor,
  'score-radio-dust': patch_score_radio_dust,
  'score-remote-orchestra': patch_score_remote_orchestra,
  'score-round-foundation': patch_score_round_foundation,
  'score-rubber-key': patch_score_rubber_key,
  'score-rust-ensemble': patch_score_rust_ensemble,
  'score-rusted-tine': patch_score_rusted_tine,
  'score-salt-violins': patch_score_salt_violins,
  'score-shortwave-chord': patch_score_shortwave_chord,
  'score-silk-swish': patch_score_silk_swish,
  'score-silt-contrabass': patch_score_silt_contrabass,
  'score-silt-pulse-bass': patch_score_silt_pulse_bass,
  'score-silver-dust': patch_score_silver_dust,
  'score-sine-weight': patch_score_sine_weight,
  'score-slow-air-riser': patch_score_slow_air_riser,
  'score-slow-beacon': patch_score_slow_beacon,
  'score-soft-machinery': patch_score_soft_machinery,
  'score-soft-undertow': patch_score_soft_undertow,
  'score-stone-marimba': patch_score_stone_marimba,
  'score-submerged-keys': patch_score_submerged_keys,
  'score-suspended-steel': patch_score_suspended_steel,
  'score-tape-halo': patch_score_tape_halo,
  'score-tidal-memory': patch_score_tidal_memory,
  'score-tin-kalimba': patch_score_tin_kalimba,
  'score-tunnel-growl': patch_score_tunnel_growl,
  'score-underwater-room': patch_score_underwater_room,
  'score-uneasy-scale': patch_score_uneasy_scale,
  'score-velvet-airlock': patch_score_velvet_airlock,
  'score-velvet-offbeat': patch_score_velvet_offbeat,
  'score-vent-breath': patch_score_vent_breath,
  'score-violet-section': patch_score_violet_section,
  'score-warm-pressure': patch_score_warm_pressure,
  'score-wire-harmonics': patch_score_wire_harmonics,
  'score-wire-harp': patch_score_wire_harp,
  'score-wire-stress': patch_score_wire_stress,
  'score-wooden-pin': patch_score_wooden_pin,
  snare: patch_snare,
  'sub-drone': patch_sub_drone,
  'tr808-clap': patch_tr808_clap,
  'tr808-clave': patch_tr808_clave,
  'tr808-conga': patch_tr808_conga,
  'tr808-cowbell': patch_tr808_cowbell,
  'tr808-cymbal': patch_tr808_cymbal,
  'tr808-hat-closed': patch_tr808_hat_closed,
  'tr808-hat-open': patch_tr808_hat_open,
  'tr808-kick-long': patch_tr808_kick_long,
  'tr808-kick': patch_tr808_kick,
  'tr808-maracas': patch_tr808_maracas,
  'tr808-rimshot': patch_tr808_rimshot,
  'tr808-snare': patch_tr808_snare,
  'tr808-tom-high': patch_tr808_tom_high,
  'tr808-tom-low': patch_tr808_tom_low,
  'tr808-tom-mid': patch_tr808_tom_mid,
  'tr909-clap': patch_tr909_clap,
  'tr909-crash': patch_tr909_crash,
  'tr909-hat-closed': patch_tr909_hat_closed,
  'tr909-hat-open': patch_tr909_hat_open,
  'tr909-kick-hard': patch_tr909_kick_hard,
  'tr909-kick': patch_tr909_kick,
  'tr909-ride': patch_tr909_ride,
  'tr909-rimshot': patch_tr909_rimshot,
  'tr909-snare': patch_tr909_snare,
  'tr909-tom-high': patch_tr909_tom_high,
  'tr909-tom-low': patch_tr909_tom_low,
  'weapon-zap': patch_weapon_zap,
};
