// Generated by scripts/patch-library-index.mjs from the files beside it — do not edit.
// `node scripts/patch-library-index.mjs --write` regenerates it; `npm run verify` checks it.
// One static import per patch is what Vite, esbuild and Vitest all bundle (#561).
import patchAiVoice from './ai-voice.json';
import patchBassDigital from './bass-digital.json';
import patchBuildThunk from './build-thunk.json';
import patchDroneSqr from './drone-sqr.json';
import patchHat from './hat.json';
import patchHordeHorn from './horde-horn.json';
import patchKick from './kick.json';
import patchLeadBell from './lead-bell.json';
import patchPadDrift from './pad-drift.json';
import patchPickupBlip from './pickup-blip.json';
import patchSawArp from './saw-arp.json';
import patchScoreAfterimageQuartet from './score-afterimage-quartet.json';
import patchScoreAmberCeiling from './score-amber-ceiling.json';
import patchScoreAmberStab from './score-amber-stab.json';
import patchScoreAshCathedral from './score-ash-cathedral.json';
import patchScoreBlackIceStrings from './score-black-ice-strings.json';
import patchScoreBlackResonator from './score-black-resonator.json';
import patchScoreBlueVapour from './score-blue-vapour.json';
import patchScoreBreathingRosin from './score-breathing-rosin.json';
import patchScoreBrightAirRiser from './score-bright-air-riser.json';
import patchScoreBrokenRelay from './score-broken-relay.json';
import patchScoreBronzeRain from './score-bronze-rain.json';
import patchScoreBufferDrift from './score-buffer-drift.json';
import patchScoreBuriedVoices from './score-buried-voices.json';
import patchScoreCarbonReed from './score-carbon-reed.json';
import patchScoreConcreteChord from './score-concrete-chord.json';
import patchScoreCopperStep from './score-copper-step.json';
import patchScoreCorruptClock from './score-corrupt-clock.json';
import patchScoreDataFragments from './score-data-fragments.json';
import patchScoreDeepCurrent from './score-deep-current.json';
import patchScoreDeepStatic from './score-deep-static.json';
import patchScoreDistantGantry from './score-distant-gantry.json';
import patchScoreDocksideBass from './score-dockside-bass.json';
import patchScoreDrownedCellos from './score-drowned-cellos.json';
import patchScoreDryRelay from './score-dry-relay.json';
import patchScoreDryTicker from './score-dry-ticker.json';
import patchScoreEmptyStation from './score-empty-station.json';
import patchScoreEnginePulser from './score-engine-pulser.json';
import patchScoreEstuaryViolas from './score-estuary-violas.json';
import patchScoreFadedNeon from './score-faded-neon.json';
import patchScoreFeltCircuit from './score-felt-circuit.json';
import patchScoreFeltSub from './score-felt-sub.json';
import patchScoreFrozenBow from './score-frozen-bow.json';
import patchScoreGhostFormants from './score-ghost-formants.json';
import patchScoreGlassHorizon from './score-glass-horizon.json';
import patchScoreGlassPebble from './score-glass-pebble.json';
import patchScoreGranularHiss from './score-granular-hiss.json';
import patchScoreGraphiteBass from './score-graphite-bass.json';
import patchScoreHarbourFog from './score-harbour-fog.json';
import patchScoreHighTremolo from './score-high-tremolo.json';
import patchScoreHollowAnchor from './score-hollow-anchor.json';
import patchScoreHollowBows from './score-hollow-bows.json';
import patchScoreHollowDroplet from './score-hollow-droplet.json';
import patchScoreHollowTicker from './score-hollow-ticker.json';
import patchScoreIceNeedle from './score-ice-needle.json';
import patchScoreIronRoot from './score-iron-root.json';
import patchScoreLastLightBell from './score-last-light-bell.json';
import patchScoreLongDownwash from './score-long-downwash.json';
import patchScoreLongDusk from './score-long-dusk.json';
import patchScoreLowTransformer from './score-low-transformer.json';
import patchScoreLowTremolo from './score-low-tremolo.json';
import patchScoreLowWeather from './score-low-weather.json';
import patchScoreMagneticVeil from './score-magnetic-veil.json';
import patchScoreMossStab from './score-moss-stab.json';
import patchScoreMutedCable from './score-muted-cable.json';
import patchScoreMutedChamber from './score-muted-chamber.json';
import patchScoreNarrowRiser from './score-narrow-riser.json';
import patchScoreNightChoir from './score-night-choir.json';
import patchScoreNightRubber from './score-night-rubber.json';
import patchScoreOpenSea from './score-open-sea.json';
import patchScorePaleMonolith from './score-pale-monolith.json';
import patchScorePassingVapour from './score-passing-vapour.json';
import patchScorePolarBloom from './score-polar-bloom.json';
import patchScorePorcelainDrop from './score-porcelain-drop.json';
import patchScoreQuickDownwash from './score-quick-downwash.json';
import patchScoreQuietReactor from './score-quiet-reactor.json';
import patchScoreRadioDust from './score-radio-dust.json';
import patchScoreRemoteOrchestra from './score-remote-orchestra.json';
import patchScoreRoundFoundation from './score-round-foundation.json';
import patchScoreRubberKey from './score-rubber-key.json';
import patchScoreRustEnsemble from './score-rust-ensemble.json';
import patchScoreRustedTine from './score-rusted-tine.json';
import patchScoreSaltViolins from './score-salt-violins.json';
import patchScoreShortwaveChord from './score-shortwave-chord.json';
import patchScoreSilkSwish from './score-silk-swish.json';
import patchScoreSiltContrabass from './score-silt-contrabass.json';
import patchScoreSiltPulseBass from './score-silt-pulse-bass.json';
import patchScoreSilverDust from './score-silver-dust.json';
import patchScoreSineWeight from './score-sine-weight.json';
import patchScoreSlowAirRiser from './score-slow-air-riser.json';
import patchScoreSlowBeacon from './score-slow-beacon.json';
import patchScoreSoftMachinery from './score-soft-machinery.json';
import patchScoreSoftUndertow from './score-soft-undertow.json';
import patchScoreStoneMarimba from './score-stone-marimba.json';
import patchScoreSubmergedKeys from './score-submerged-keys.json';
import patchScoreSuspendedSteel from './score-suspended-steel.json';
import patchScoreTapeHalo from './score-tape-halo.json';
import patchScoreTidalMemory from './score-tidal-memory.json';
import patchScoreTinKalimba from './score-tin-kalimba.json';
import patchScoreTunnelGrowl from './score-tunnel-growl.json';
import patchScoreUnderwaterRoom from './score-underwater-room.json';
import patchScoreUneasyScale from './score-uneasy-scale.json';
import patchScoreVelvetAirlock from './score-velvet-airlock.json';
import patchScoreVelvetOffbeat from './score-velvet-offbeat.json';
import patchScoreVentBreath from './score-vent-breath.json';
import patchScoreVioletSection from './score-violet-section.json';
import patchScoreWarmPressure from './score-warm-pressure.json';
import patchScoreWireHarmonics from './score-wire-harmonics.json';
import patchScoreWireHarp from './score-wire-harp.json';
import patchScoreWireStress from './score-wire-stress.json';
import patchScoreWoodenPin from './score-wooden-pin.json';
import patchSnare from './snare.json';
import patchSubDrone from './sub-drone.json';
import patchWeaponZap from './weapon-zap.json';

/** Every library file, raw and unvalidated, keyed by id (`presets.ts` loads it). */
export const PATCH_FILES: Readonly<Record<string, unknown>> = {
  'ai-voice': patchAiVoice,
  'bass-digital': patchBassDigital,
  'build-thunk': patchBuildThunk,
  'drone-sqr': patchDroneSqr,
  hat: patchHat,
  'horde-horn': patchHordeHorn,
  kick: patchKick,
  'lead-bell': patchLeadBell,
  'pad-drift': patchPadDrift,
  'pickup-blip': patchPickupBlip,
  'saw-arp': patchSawArp,
  'score-afterimage-quartet': patchScoreAfterimageQuartet,
  'score-amber-ceiling': patchScoreAmberCeiling,
  'score-amber-stab': patchScoreAmberStab,
  'score-ash-cathedral': patchScoreAshCathedral,
  'score-black-ice-strings': patchScoreBlackIceStrings,
  'score-black-resonator': patchScoreBlackResonator,
  'score-blue-vapour': patchScoreBlueVapour,
  'score-breathing-rosin': patchScoreBreathingRosin,
  'score-bright-air-riser': patchScoreBrightAirRiser,
  'score-broken-relay': patchScoreBrokenRelay,
  'score-bronze-rain': patchScoreBronzeRain,
  'score-buffer-drift': patchScoreBufferDrift,
  'score-buried-voices': patchScoreBuriedVoices,
  'score-carbon-reed': patchScoreCarbonReed,
  'score-concrete-chord': patchScoreConcreteChord,
  'score-copper-step': patchScoreCopperStep,
  'score-corrupt-clock': patchScoreCorruptClock,
  'score-data-fragments': patchScoreDataFragments,
  'score-deep-current': patchScoreDeepCurrent,
  'score-deep-static': patchScoreDeepStatic,
  'score-distant-gantry': patchScoreDistantGantry,
  'score-dockside-bass': patchScoreDocksideBass,
  'score-drowned-cellos': patchScoreDrownedCellos,
  'score-dry-relay': patchScoreDryRelay,
  'score-dry-ticker': patchScoreDryTicker,
  'score-empty-station': patchScoreEmptyStation,
  'score-engine-pulser': patchScoreEnginePulser,
  'score-estuary-violas': patchScoreEstuaryViolas,
  'score-faded-neon': patchScoreFadedNeon,
  'score-felt-circuit': patchScoreFeltCircuit,
  'score-felt-sub': patchScoreFeltSub,
  'score-frozen-bow': patchScoreFrozenBow,
  'score-ghost-formants': patchScoreGhostFormants,
  'score-glass-horizon': patchScoreGlassHorizon,
  'score-glass-pebble': patchScoreGlassPebble,
  'score-granular-hiss': patchScoreGranularHiss,
  'score-graphite-bass': patchScoreGraphiteBass,
  'score-harbour-fog': patchScoreHarbourFog,
  'score-high-tremolo': patchScoreHighTremolo,
  'score-hollow-anchor': patchScoreHollowAnchor,
  'score-hollow-bows': patchScoreHollowBows,
  'score-hollow-droplet': patchScoreHollowDroplet,
  'score-hollow-ticker': patchScoreHollowTicker,
  'score-ice-needle': patchScoreIceNeedle,
  'score-iron-root': patchScoreIronRoot,
  'score-last-light-bell': patchScoreLastLightBell,
  'score-long-downwash': patchScoreLongDownwash,
  'score-long-dusk': patchScoreLongDusk,
  'score-low-transformer': patchScoreLowTransformer,
  'score-low-tremolo': patchScoreLowTremolo,
  'score-low-weather': patchScoreLowWeather,
  'score-magnetic-veil': patchScoreMagneticVeil,
  'score-moss-stab': patchScoreMossStab,
  'score-muted-cable': patchScoreMutedCable,
  'score-muted-chamber': patchScoreMutedChamber,
  'score-narrow-riser': patchScoreNarrowRiser,
  'score-night-choir': patchScoreNightChoir,
  'score-night-rubber': patchScoreNightRubber,
  'score-open-sea': patchScoreOpenSea,
  'score-pale-monolith': patchScorePaleMonolith,
  'score-passing-vapour': patchScorePassingVapour,
  'score-polar-bloom': patchScorePolarBloom,
  'score-porcelain-drop': patchScorePorcelainDrop,
  'score-quick-downwash': patchScoreQuickDownwash,
  'score-quiet-reactor': patchScoreQuietReactor,
  'score-radio-dust': patchScoreRadioDust,
  'score-remote-orchestra': patchScoreRemoteOrchestra,
  'score-round-foundation': patchScoreRoundFoundation,
  'score-rubber-key': patchScoreRubberKey,
  'score-rust-ensemble': patchScoreRustEnsemble,
  'score-rusted-tine': patchScoreRustedTine,
  'score-salt-violins': patchScoreSaltViolins,
  'score-shortwave-chord': patchScoreShortwaveChord,
  'score-silk-swish': patchScoreSilkSwish,
  'score-silt-contrabass': patchScoreSiltContrabass,
  'score-silt-pulse-bass': patchScoreSiltPulseBass,
  'score-silver-dust': patchScoreSilverDust,
  'score-sine-weight': patchScoreSineWeight,
  'score-slow-air-riser': patchScoreSlowAirRiser,
  'score-slow-beacon': patchScoreSlowBeacon,
  'score-soft-machinery': patchScoreSoftMachinery,
  'score-soft-undertow': patchScoreSoftUndertow,
  'score-stone-marimba': patchScoreStoneMarimba,
  'score-submerged-keys': patchScoreSubmergedKeys,
  'score-suspended-steel': patchScoreSuspendedSteel,
  'score-tape-halo': patchScoreTapeHalo,
  'score-tidal-memory': patchScoreTidalMemory,
  'score-tin-kalimba': patchScoreTinKalimba,
  'score-tunnel-growl': patchScoreTunnelGrowl,
  'score-underwater-room': patchScoreUnderwaterRoom,
  'score-uneasy-scale': patchScoreUneasyScale,
  'score-velvet-airlock': patchScoreVelvetAirlock,
  'score-velvet-offbeat': patchScoreVelvetOffbeat,
  'score-vent-breath': patchScoreVentBreath,
  'score-violet-section': patchScoreVioletSection,
  'score-warm-pressure': patchScoreWarmPressure,
  'score-wire-harmonics': patchScoreWireHarmonics,
  'score-wire-harp': patchScoreWireHarp,
  'score-wire-stress': patchScoreWireStress,
  'score-wooden-pin': patchScoreWoodenPin,
  snare: patchSnare,
  'sub-drone': patchSubDrone,
  'weapon-zap': patchWeaponZap,
};
