/**
 * The pure half of `scripts/patch-library-index.mjs` (#561): which files in
 * `packages/client/src/audio/patches/` are patches, and the text of the
 * `index.ts` that imports every one of them statically. Static imports are the
 * one mechanism Vite (the game), esbuild (the standalone editor) and Vitest
 * share — `import.meta.glob` is Vite-only — so the index is generated and
 * `npm run verify` refuses a stale one, the way `client-dir-table.mjs` does.
 */
import { readdirSync } from 'node:fs';

/** A filename slug — the same rule `patchLibrary.ts` enforces on load. */
export const PATCH_ID_RULE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** The ids of every `<id>.json` in `dir`, sorted; throws on a file that is not a patch slug. */
export function patchIdsIn(dir) {
  const ids = [];
  for (const name of readdirSync(dir).sort()) {
    if (name === 'index.ts') continue;
    if (!name.endsWith('.json'))
      throw new Error(`${dir}/${name}: only <id>.json files belong here`);
    const id = name.slice(0, -'.json'.length);
    if (!PATCH_ID_RULE.test(id))
      throw new Error(`${dir}/${name}: "${id}" is not a slug (lower-case words joined by hyphens)`);
    ids.push(id);
  }
  return ids;
}

/** `score-drowned-cellos` → `patchScoreDrownedCellos`: a prefix keeps a slug like `new` legal. */
export const identifierFor = (id) =>
  'patch' + id.replace(/(^|-)([a-z0-9])/g, (_, __, letter) => letter.toUpperCase());

/** The generated module: one default import per file, one map keyed by id. */
export function renderIndex(ids) {
  const lines = [
    '// Generated by scripts/patch-library-index.mjs from the files beside it — do not edit.',
    '// `node scripts/patch-library-index.mjs --write` regenerates it; `npm run verify` checks it.',
    '// One static import per patch is what Vite, esbuild and Vitest all bundle (#561).',
  ];
  for (const id of ids) lines.push(`import ${identifierFor(id)} from './${id}.json';`);
  lines.push(
    '',
    '/** Every library file, raw and unvalidated, keyed by id (`presets.ts` loads it). */',
  );
  lines.push('export const PATCH_FILES: Readonly<Record<string, unknown>> = {');
  // Prettier's quoteProps is "as-needed": a plain word is an unquoted key.
  for (const id of ids) lines.push(`  ${id.includes('-') ? `'${id}'` : id}: ${identifierFor(id)},`);
  lines.push('};', '');
  return lines.join('\n');
}
