#!/usr/bin/env python3
"""Codex review rounds and PR size for Windsor's merged PRs, from GitHub.

Stdlib only; needs an authenticated `gh`. Reads every merged PR from #18
(the first under the parallel workflow) whose merge is at or before --until,
and prints a markdown report. Only counts and timestamps are printed, never
comment text.

- Extra rounds: commits on the PR minus one. A proxy: a fix round is
  usually one commit, but a rebase or a second commit in one round also
  counts.
- Codex latency: from the PR's newest commit before a Codex review (or a
  Codex issue comment: its summary or its no-findings note) to that
  review. Commit time, not push time: a push after the commit makes this
  longer than the wait after the push, so it is an upper bound on that.
- Every Codex event after --until is left out, like every PR merged after
  it, so a rerun reproduces the report.
- P0/P1: Codex inline comments whose badge names P0 or P1.

    python3 pr-rounds.py [--until 2026-09-29T09:22:00Z] > pr-report.md
"""

import json
import re
import subprocess
import sys
from datetime import datetime

REPO = "tacowars/windsor"
FIRST_PR = 18
UNTIL = "2026-09-29T09:22:00Z"
SIZE_BANDS = [(0, 300), (300, 1000), (1000, None)]


def ts(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def gh(*args):
    out = subprocess.run(["gh", *args], capture_output=True, text=True, check=True).stdout
    return json.loads(out)


def api(path):
    pages = gh("api", path, "--paginate", "--slurp")
    return [x for page in pages for x in page]


def is_codex(user):
    return "codex" in user["login"].lower()


def median(xs):
    xs = sorted(xs)
    return xs[len(xs) // 2] if xs else 0


def main():
    until = ts(sys.argv[sys.argv.index("--until") + 1] if "--until" in sys.argv else UNTIL)
    prs = gh("pr", "list", "--repo", REPO, "--state", "merged", "--limit", "200",
             "--json", "number,title,createdAt,mergedAt,additions,deletions")
    prs = sorted((p for p in prs if p["number"] >= FIRST_PR and ts(p["mergedAt"]) <= until),
                 key=lambda p: p["number"])
    rows, latency = [], []
    for p in prs:
        n = p["number"]
        commits = sorted(ts(c["commit"]["committer"]["date"]) for c in api(f"repos/{REPO}/pulls/{n}/commits"))
        reviews = [r for r in api(f"repos/{REPO}/pulls/{n}/reviews")
                   if is_codex(r["user"]) and r.get("submitted_at") and ts(r["submitted_at"]) <= until]
        inline = [c for c in api(f"repos/{REPO}/pulls/{n}/comments")
                  if is_codex(c["user"]) and ts(c["created_at"]) <= until]
        notes = [c for c in api(f"repos/{REPO}/issues/{n}/comments")
                 if is_codex(c["user"]) and ts(c["created_at"]) <= until]
        for at in sorted([ts(r["submitted_at"]) for r in reviews] + [ts(c["created_at"]) for c in notes]):
            before = [c for c in commits if c < at]
            if before:
                latency.append((at - before[-1]).total_seconds() / 60)
        p1 = sum(1 for c in inline if re.search(r"P[01]\b", c["body"][:120]))
        rows.append(dict(n=n, lines=p["additions"] + p["deletions"], extra=len(commits) - 1,
                         p1=p1, hours=(ts(p["mergedAt"]) - ts(p["createdAt"])).total_seconds() / 3600,
                         title=p["title"]))
    out = [f"# Codex rounds and PR size, merged PRs #{FIRST_PR} onward, up to {until.isoformat()}\n",
           "Generated by `pr-rounds.py` from the GitHub API.\n",
           "| PR | changed lines | extra rounds | Codex P0/P1 | open to merge |",
           "|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| #{r['n']} | {r['lines']} | {r['extra']} | {r['p1']} | {r['hours']:.1f} h |")
    out.append("")
    out.append(f"- Merged PRs: {len(rows)}. With at least one Codex P0/P1: {sum(1 for r in rows if r['p1'])}; "
               f"P0/P1 findings in total: {sum(r['p1'] for r in rows)}.")
    dist = {}
    for r in rows:
        dist[min(r["extra"], 3)] = dist.get(min(r["extra"], 3), 0) + 1
    out.append("- Extra rounds (3 means 3 or more): " + ", ".join(f"{k}: {v}" for k, v in sorted(dist.items())) + ".")
    lat = sorted(latency)
    out.append(f"- Codex latency after the newest commit (an upper bound on the wait after a push): median {median(lat):.1f} min, p90 {lat[int(len(lat) * 0.9)]:.1f} min, "
               f"n = {len(lat)}.")
    for lo, hi in SIZE_BANDS:
        band = [r for r in rows if r["lines"] >= lo and (hi is None or r["lines"] < hi)]
        label = f"{lo}+" if hi is None else f"{lo}-{hi - 1}"
        if band:
            out.append(f"- {label} changed lines: n = {len(band)}, mean extra rounds "
                       f"{sum(r['extra'] for r in band) / len(band):.2f}, past the two-round cap "
                       f"{sum(1 for r in band if r['extra'] > 2)}.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
